services:

  caddy:
    image: caddy:2-alpine
    container_name: group4-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

  frontend:
    build:
      context: ./app/frontend
    container_name: group4-frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
    container_name: group4-backend
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  caddy_data:
  caddy_config:
